# Generated by Django 4.1.3 on 2022-11-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Гос номер')),
                ('vin', models.CharField(max_length=20, unique=True, verbose_name='VIN номер')),
                ('sts_number', models.CharField(max_length=20, unique=True, verbose_name='СТС серия и номер')),
                ('sts_photo', models.ImageField(upload_to='', verbose_name='Фото СТС')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('fine', models.IntegerField(default=0, verbose_name='Штраф')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('info', models.TextField(max_length=300)),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('max_count', models.IntegerField(verbose_name='Максимальное количество мест')),
                ('count', models.IntegerField(default=0, verbose_name='Количество занятых мест')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='API.car')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
