# Generated by Django 4.1.3 on 2022-11-19 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esia_id', models.IntegerField(blank=True, null=True, verbose_name='ID пользователя в ГосУслугах')),
                ('first_name', models.CharField(default='Герман', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default='Багдасарян', max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('email', models.CharField(max_length=100, verbose_name='e-mail')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('favorite_station', models.ManyToManyField(blank=True, to='API.station', verbose_name='Избранные станции')),
                ('garage', models.ManyToManyField(blank=True, to='API.car')),
                ('notifications', models.ManyToManyField(blank=True, to='API.notification', verbose_name='Уведомления')),
                ('requests', models.ManyToManyField(blank=True, to='API.requests', verbose_name='История запросов')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('dislikes', models.IntegerField(default=0, verbose_name='dislikes')),
                ('content', models.TextField(verbose_name='Контент')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reviews', models.ManyToManyField(blank=True, to='UI.user')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
